// Budget rollover engine (spec 027 — the rollover slice of §4.1).
//
// Pure, integer-USD-cents money math, regression-vector-locked by
// `shared/test-vectors/budget-rollover.json` (generated by
// `scripts/gen-vectors.ts`, asserted by `test/budget-rollover.parity.test.ts`).
// Carry is DERIVED from history on every render — never stored, no month-close
// job — so the model can't drift and works offline. See
// `specs/027-budget-rollover/contracts/rollover-math.md`.

import type { Budget, BudgetType, Transaction } from '../types'

export interface RolloverConfig {
  type: BudgetType
  /** Base monthly allowance, integer cents, >= 0. */
  baseLimitCents: number
  /** Flex-only cap on ACCUMULATED carry; null = uncapped. Ignored for other types. */
  rolloverCapCents: number | null
  /** Carry brought into the first month (default 0). */
  openingCarryCents?: number
}

export interface RolloverMonth {
  carriedInCents: number
  baseLimitCents: number
  /** base + carriedIn */
  effectiveLimitCents: number
  spentCents: number
  /** effective − spent (may be negative) */
  remainingCents: number
  /** what rolls into next month */
  carriedOutCents: number
}

/**
 * Run the rollover recurrence over an ordered series of monthly spends, one
 * output entry per input month. The three carry rules:
 *
 * - `fixed`       — no carry (carriedIn/Out always 0); effective === base.
 * - `flex`        — surplus-only, optionally capped: carriedOut =
 *                   min(cap, max(0, remaining)). An overspend is forgiven.
 * - `non_monthly` — full signed carry, uncapped: carriedOut = remaining. A
 *                   sinking fund; a shortfall carries as a negative.
 */
export function computeRolloverLedger(
  config: RolloverConfig,
  monthlySpendCents: number[],
): RolloverMonth[] {
  const { type, baseLimitCents, rolloverCapCents } = config
  const opening = config.openingCarryCents ?? 0

  const out: RolloverMonth[] = []
  let prevCarriedOut = opening

  for (let m = 0; m < monthlySpendCents.length; m++) {
    const spent = monthlySpendCents[m]
    const carriedIn = type === 'fixed' ? 0 : m === 0 ? opening : prevCarriedOut
    const effective = baseLimitCents + carriedIn
    const remaining = effective - spent

    let carriedOut: number
    if (type === 'fixed') {
      carriedOut = 0
    } else if (type === 'flex') {
      const surplus = Math.max(0, remaining)
      carriedOut = rolloverCapCents == null ? surplus : Math.min(rolloverCapCents, surplus)
    } else {
      // non_monthly: signed, uncapped sinking fund
      carriedOut = remaining
    }

    out.push({
      carriedInCents: carriedIn,
      baseLimitCents,
      effectiveLimitCents: effective,
      spentCents: spent,
      remainingCents: remaining,
      carriedOutCents: carriedOut,
    })
    prevCarriedOut = carriedOut
  }

  return out
}

export interface BudgetStatus {
  effectiveLimitCents: number
  spentCents: number
  /** effective − spent for the reference month (may be negative). */
  remainingCents: number
  carriedInCents: number
}

/** Local-calendar month key `YYYY-MM` (matches insights.ts / BudgetProgressCard bucketing). */
function monthKey(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

/** Whole months from `a` to `b` (b >= a), by local calendar. Negative if b < a. */
function monthsBetween(a: Date, b: Date): number {
  return (b.getFullYear() - a.getFullYear()) * 12 + (b.getMonth() - a.getMonth())
}

/**
 * The full rollover ledger for one budget, one entry per month from its
 * creation month through `referenceMonth` (spec 057, D8). The carry anchor is
 * the budget's creation month (months before it existed contribute nothing);
 * spend is bucketed by local calendar month exactly like the
 * dashboard/insights. All arithmetic is delegated to `computeRolloverLedger`
 * — this adapter only reduces the ledger to the monthly-spend series, so it
 * needs no golden vector of its own.
 *
 * `budgetStatusForMonth` computed exactly this series already and kept only
 * its last entry, discarding the carry history on every render. This is a
 * pure extraction, not new behaviour: `budgetStatusForMonth`'s own tests are
 * the pin, and this function's last entry must always equal its return.
 */
export function budgetLedgerForMonth(
  budget: Budget,
  transactions: Transaction[],
  referenceMonth: Date,
): RolloverMonth[] {
  // Anchor = creation month, but never later than the reference month (a budget
  // viewed in a month before it was created still yields a sane zero-carry status).
  const created = budget.created_at ? new Date(budget.created_at) : referenceMonth
  const anchor =
    monthsBetween(created, referenceMonth) < 0
      ? new Date(referenceMonth.getFullYear(), referenceMonth.getMonth(), 1)
      : new Date(created.getFullYear(), created.getMonth(), 1)

  const monthCount = monthsBetween(anchor, referenceMonth) + 1

  // Sum expense spend for this category into each month bucket in [anchor, ref].
  const spendByMonth = new Map<string, number>()
  for (const tx of transactions) {
    if (tx.kind !== 'expense' || tx.category !== budget.category) continue
    const d = new Date(tx.date)
    if (monthsBetween(anchor, d) < 0 || monthsBetween(d, referenceMonth) < 0) continue
    const k = monthKey(d)
    spendByMonth.set(k, (spendByMonth.get(k) ?? 0) + tx.amount_cents)
  }

  const series: number[] = []
  for (let i = 0; i < monthCount; i++) {
    const d = new Date(anchor.getFullYear(), anchor.getMonth() + i, 1)
    series.push(spendByMonth.get(monthKey(d)) ?? 0)
  }

  return computeRolloverLedger(
    {
      type: budget.budget_type,
      baseLimitCents: budget.monthly_limit_cents,
      rolloverCapCents: budget.rollover_cap_cents,
    },
    series,
  )
}

/**
 * Rollover-aware status of one budget for `referenceMonth` — the last entry
 * of `budgetLedgerForMonth`'s full series (spec 057, D8).
 */
export function budgetStatusForMonth(
  budget: Budget,
  transactions: Transaction[],
  referenceMonth: Date,
): BudgetStatus {
  const ledger = budgetLedgerForMonth(budget, transactions, referenceMonth)
  const last = ledger[ledger.length - 1]
  return {
    effectiveLimitCents: last.effectiveLimitCents,
    spentCents: last.spentCents,
    remainingCents: last.remainingCents,
    carriedInCents: last.carriedInCents,
  }
}
