// Golden-vector regression lock for the budget rollover engine (spec 027).
// Fixtures are generated by scripts/gen-vectors.ts from lib/finance/budgets.ts;
// this asserts the engine reproduces them and that the structural invariants
// hold. See specs/027-budget-rollover/contracts/rollover-math.md.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import {
  computeRolloverLedger,
  type RolloverConfig,
  type RolloverMonth,
} from '../lib/finance/budgets'

const here = dirname(fileURLToPath(import.meta.url))
const vectors = JSON.parse(
  readFileSync(resolve(here, '../../shared/test-vectors/budget-rollover.json'), 'utf8'),
) as Array<{
  input: { name: string; config: RolloverConfig; monthlySpendCents: number[] }
  expected: RolloverMonth[]
}>

describe('budget rollover parity vs golden vectors', () => {
  for (const { input, expected } of vectors) {
    it(input.name, () => {
      const actual = computeRolloverLedger(input.config, input.monthlySpendCents)
      expect(actual).toEqual(expected)

      // Structural invariants (contract rollover-math.md).
      for (const m of actual) {
        expect(m.effectiveLimitCents).toBe(m.baseLimitCents + m.carriedInCents)
        expect(m.remainingCents).toBe(m.effectiveLimitCents - m.spentCents)
        expect(Number.isInteger(m.carriedOutCents)).toBe(true)
        expect(Number.isInteger(m.remainingCents)).toBe(true)
        if (input.config.type === 'fixed') {
          expect(m.carriedInCents).toBe(0)
          expect(m.carriedOutCents).toBe(0)
          expect(m.effectiveLimitCents).toBe(m.baseLimitCents)
        } else if (input.config.type === 'flex') {
          expect(m.carriedOutCents).toBeGreaterThanOrEqual(0)
          if (input.config.rolloverCapCents != null) {
            expect(m.carriedOutCents).toBeLessThanOrEqual(input.config.rolloverCapCents)
          }
        } else {
          // non_monthly: signed carry equals remaining
          expect(m.carriedOutCents).toBe(m.remainingCents)
        }
      }
    })
  }
})
